services:
  db:
    image: postgres:16-alpine
    container_name: iugm_postgres_db
    restart: always
    # Charge le fichier d'environnement de Next.js pour Docker
    env_file:
      - .env.local
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - iugm_db_data:/var/lib/postgresql/data

volumes:
  iugm_db_data: